set(_CATKIN_CURRENT_PACKAGE "tfr_monitoring")
set(tfr_monitoring_VERSION "0.0.0")
set(tfr_monitoring_MAINTAINER "carla <carla@todo.todo>")
set(tfr_monitoring_PACKAGE_FORMAT "2")
set(tfr_monitoring_BUILD_DEPENDS )
set(tfr_monitoring_BUILD_EXPORT_DEPENDS )
set(tfr_monitoring_BUILDTOOL_DEPENDS "catkin")
set(tfr_monitoring_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_monitoring_EXEC_DEPENDS )
set(tfr_monitoring_RUN_DEPENDS )
set(tfr_monitoring_TEST_DEPENDS )
set(tfr_monitoring_DOC_DEPENDS )
set(tfr_monitoring_URL_WEBSITE "")
set(tfr_monitoring_URL_BUGTRACKER "")
set(tfr_monitoring_URL_REPOSITORY "")
set(tfr_monitoring_DEPRECATED "")