// do not edit! This is an autogenerated file (see regenerate_markers.py in the aruco folder)
void setBoardData(std::vector<std::vector<cv::Point3f> > &boardCorners, std::vector<int> &boardIds)
{
	std::vector<cv::Point3f> markerPoints;
	markerPoints = 
	{
	cv::Point3f(-0.105, 0.02, 0),
	cv::Point3f(0.08, 0.02, 0),
	cv::Point3f(0.08, 0.205, 0),
	cv::Point3f(-0.105, 0.205, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(1);

	markerPoints = 
	{
	cv::Point3f(-0.1035, 0.2085, 0),
	cv::Point3f(-0.0755, 0.2085, 0),
	cv::Point3f(-0.0755, 0.2365, 0),
	cv::Point3f(-0.1035, 0.2365, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(2);

	markerPoints = 
	{
	cv::Point3f(-0.1035, 0.2395, 0),
	cv::Point3f(-0.0755, 0.2395, 0),
	cv::Point3f(-0.0755, 0.2675, 0),
	cv::Point3f(-0.1035, 0.2675, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(3);

	markerPoints = 
	{
	cv::Point3f(-0.1035, 0.2705, 0),
	cv::Point3f(-0.0755, 0.2705, 0),
	cv::Point3f(-0.0755, 0.2985, 0),
	cv::Point3f(-0.1035, 0.2985, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(4);

	markerPoints = 
	{
	cv::Point3f(-0.0725, 0.2085, 0),
	cv::Point3f(-0.0445, 0.2085, 0),
	cv::Point3f(-0.0445, 0.2365, 0),
	cv::Point3f(-0.0725, 0.2365, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(5);

	markerPoints = 
	{
	cv::Point3f(-0.0725, 0.2395, 0),
	cv::Point3f(-0.0445, 0.2395, 0),
	cv::Point3f(-0.0445, 0.2675, 0),
	cv::Point3f(-0.0725, 0.2675, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(6);

	markerPoints = 
	{
	cv::Point3f(-0.0725, 0.2705, 0),
	cv::Point3f(-0.0445, 0.2705, 0),
	cv::Point3f(-0.0445, 0.2985, 0),
	cv::Point3f(-0.0725, 0.2985, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(7);

	markerPoints = 
	{
	cv::Point3f(-0.0415, 0.2085, 0),
	cv::Point3f(-0.0135, 0.2085, 0),
	cv::Point3f(-0.0135, 0.2365, 0),
	cv::Point3f(-0.0415, 0.2365, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(8);

	markerPoints = 
	{
	cv::Point3f(-0.0415, 0.2395, 0),
	cv::Point3f(-0.0135, 0.2395, 0),
	cv::Point3f(-0.0135, 0.2675, 0),
	cv::Point3f(-0.0415, 0.2675, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(9);

	markerPoints = 
	{
	cv::Point3f(-0.0415, 0.2705, 0),
	cv::Point3f(-0.0135, 0.2705, 0),
	cv::Point3f(-0.0135, 0.2985, 0),
	cv::Point3f(-0.0415, 0.2985, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(10);

	markerPoints = 
	{
	cv::Point3f(-0.0105, 0.2085, 0),
	cv::Point3f(0.0175, 0.2085, 0),
	cv::Point3f(0.0175, 0.2365, 0),
	cv::Point3f(-0.0105, 0.2365, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(11);

	markerPoints = 
	{
	cv::Point3f(-0.0105, 0.2395, 0),
	cv::Point3f(0.0175, 0.2395, 0),
	cv::Point3f(0.0175, 0.2675, 0),
	cv::Point3f(-0.0105, 0.2675, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(12);

	markerPoints = 
	{
	cv::Point3f(-0.0105, 0.2705, 0),
	cv::Point3f(0.0175, 0.2705, 0),
	cv::Point3f(0.0175, 0.2985, 0),
	cv::Point3f(-0.0105, 0.2985, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(13);

	markerPoints = 
	{
	cv::Point3f(0.0205, 0.2085, 0),
	cv::Point3f(0.0485, 0.2085, 0),
	cv::Point3f(0.0485, 0.2365, 0),
	cv::Point3f(0.0205, 0.2365, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(14);

	markerPoints = 
	{
	cv::Point3f(0.0205, 0.2395, 0),
	cv::Point3f(0.0485, 0.2395, 0),
	cv::Point3f(0.0485, 0.2675, 0),
	cv::Point3f(0.0205, 0.2675, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(15);

	markerPoints = 
	{
	cv::Point3f(0.0205, 0.2705, 0),
	cv::Point3f(0.0485, 0.2705, 0),
	cv::Point3f(0.0485, 0.2985, 0),
	cv::Point3f(0.0205, 0.2985, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(16);

	markerPoints = 
	{
	cv::Point3f(0.0515, 0.2085, 0),
	cv::Point3f(0.0795, 0.2085, 0),
	cv::Point3f(0.0795, 0.2365, 0),
	cv::Point3f(0.0515, 0.2365, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(17);

	markerPoints = 
	{
	cv::Point3f(0.0515, 0.2395, 0),
	cv::Point3f(0.0795, 0.2395, 0),
	cv::Point3f(0.0795, 0.2675, 0),
	cv::Point3f(0.0515, 0.2675, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(18);

	markerPoints = 
	{
	cv::Point3f(0.0515, 0.2705, 0),
	cv::Point3f(0.0795, 0.2705, 0),
	cv::Point3f(0.0795, 0.2985, 0),
	cv::Point3f(0.0515, 0.2985, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(19);

	markerPoints = 
	{
	cv::Point3f(0.0825, 0.2085, 0),
	cv::Point3f(0.1105, 0.2085, 0),
	cv::Point3f(0.1105, 0.2365, 0),
	cv::Point3f(0.0825, 0.2365, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(20);

	markerPoints = 
	{
	cv::Point3f(0.0825, 0.2395, 0),
	cv::Point3f(0.1105, 0.2395, 0),
	cv::Point3f(0.1105, 0.2675, 0),
	cv::Point3f(0.0825, 0.2675, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(21);

	markerPoints = 
	{
	cv::Point3f(0.0825, 0.2705, 0),
	cv::Point3f(0.1105, 0.2705, 0),
	cv::Point3f(0.1105, 0.2985, 0),
	cv::Point3f(0.0825, 0.2985, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(22);

}
