set(_CATKIN_CURRENT_PACKAGE "tfr_control")
set(tfr_control_VERSION "0.0.0")
set(tfr_control_MAINTAINER "Ryan Berge <ryan.berge@trickfirerobotics.com>, Adam Krpan <adam.krpan@outlook.com>")
set(tfr_control_PACKAGE_FORMAT "2")
set(tfr_control_BUILD_DEPENDS "roscpp" "std_msgs" "std_srvs" "geometry_msgs" "tfr_msgs" "tfr_utilities" "hardware_interface" "controller_manager" "joint_state_controller" "joint_state_publisher" "rqt_gui" "effort_controllers" "joint_trajectory_controller" "moveit_ros_planning_interface" "tf" "nav_msgs")
set(tfr_control_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "std_srvs" "geometry_msgs" "tfr_msgs" "tfr_utilities" "hardware_interface" "controller_manager" "joint_state_controller" "joint_state_publisher" "rqt_gui" "effort_controllers" "joint_trajectory_controller" "moveit_ros_planning_interface" "tf" "nav_msgs")
set(tfr_control_BUILDTOOL_DEPENDS "catkin")
set(tfr_control_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_control_EXEC_DEPENDS "roscpp" "std_msgs" "std_srvs" "geometry_msgs" "tfr_msgs" "tfr_utilities" "hardware_interface" "controller_manager" "joint_state_controller" "joint_state_publisher" "rqt_gui" "effort_controllers" "joint_trajectory_controller" "moveit_ros_planning_interface" "tf" "nav_msgs")
set(tfr_control_RUN_DEPENDS "roscpp" "std_msgs" "std_srvs" "geometry_msgs" "tfr_msgs" "tfr_utilities" "hardware_interface" "controller_manager" "joint_state_controller" "joint_state_publisher" "rqt_gui" "effort_controllers" "joint_trajectory_controller" "moveit_ros_planning_interface" "tf" "nav_msgs")
set(tfr_control_TEST_DEPENDS "gtest")
set(tfr_control_DOC_DEPENDS )
set(tfr_control_URL_WEBSITE "http://www.trickfirerobotics.com/")
set(tfr_control_URL_BUGTRACKER "")
set(tfr_control_URL_REPOSITORY "")
set(tfr_control_DEPRECATED "")