set(_CATKIN_CURRENT_PACKAGE "tfr_description")
set(tfr_description_VERSION "0.0.0")
set(tfr_description_MAINTAINER "Adam Krpan <adam.krpan@outlook.com>")
set(tfr_description_PACKAGE_FORMAT "2")
set(tfr_description_BUILD_DEPENDS )
set(tfr_description_BUILD_EXPORT_DEPENDS )
set(tfr_description_BUILDTOOL_DEPENDS "catkin")
set(tfr_description_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_description_EXEC_DEPENDS "xacro")
set(tfr_description_RUN_DEPENDS "xacro")
set(tfr_description_TEST_DEPENDS )
set(tfr_description_DOC_DEPENDS )
set(tfr_description_URL_WEBSITE "http://www.trickfirerobotics.com/")
set(tfr_description_URL_BUGTRACKER "")
set(tfr_description_URL_REPOSITORY "")
set(tfr_description_DEPRECATED "")