set(_CATKIN_CURRENT_PACKAGE "tfr_mining")
set(tfr_mining_VERSION "0.0.0")
set(tfr_mining_MAINTAINER "Ryan Berge <ryan.berge@trickfirerobotics.com>")
set(tfr_mining_PACKAGE_FORMAT "2")
set(tfr_mining_BUILD_DEPENDS "roscpp" "std_msgs" "tfr_msgs" "tfr_utilities")
set(tfr_mining_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "tfr_msgs" "tfr_utilities")
set(tfr_mining_BUILDTOOL_DEPENDS "catkin")
set(tfr_mining_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_mining_EXEC_DEPENDS "roscpp" "std_msgs" "tfr_msgs" "tfr_utilities")
set(tfr_mining_RUN_DEPENDS "roscpp" "std_msgs" "tfr_msgs" "tfr_utilities")
set(tfr_mining_TEST_DEPENDS "gtest")
set(tfr_mining_DOC_DEPENDS )
set(tfr_mining_URL_WEBSITE "http://www.trickfirerobotics.com/")
set(tfr_mining_URL_BUGTRACKER "")
set(tfr_mining_URL_REPOSITORY "")
set(tfr_mining_DEPRECATED "")