set(_CATKIN_CURRENT_PACKAGE "tfr_gazebo")
set(tfr_gazebo_VERSION "0.0.0")
set(tfr_gazebo_MAINTAINER "carla <carla@todo.todo>")
set(tfr_gazebo_PACKAGE_FORMAT "2")
set(tfr_gazebo_BUILD_DEPENDS )
set(tfr_gazebo_BUILD_EXPORT_DEPENDS )
set(tfr_gazebo_BUILDTOOL_DEPENDS "catkin")
set(tfr_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_gazebo_EXEC_DEPENDS )
set(tfr_gazebo_RUN_DEPENDS )
set(tfr_gazebo_TEST_DEPENDS )
set(tfr_gazebo_DOC_DEPENDS )
set(tfr_gazebo_URL_WEBSITE "")
set(tfr_gazebo_URL_BUGTRACKER "")
set(tfr_gazebo_URL_REPOSITORY "")
set(tfr_gazebo_DEPRECATED "")