set(_CATKIN_CURRENT_PACKAGE "tfr_executive")
set(tfr_executive_VERSION "0.0.0")
set(tfr_executive_MAINTAINER "Ryan Berge <ryan.berge@trickfirerobotics.com>")
set(tfr_executive_PACKAGE_FORMAT "2")
set(tfr_executive_BUILD_DEPENDS "roscpp" "tfr_msgs" "tfr_utilities" "geometry_msgs" "trajectory_msgs" "actionlib")
set(tfr_executive_BUILD_EXPORT_DEPENDS "roscpp" "tfr_msgs" "tfr_utilities" "geometry_msgs" "trajectory_msgs" "actionlib")
set(tfr_executive_BUILDTOOL_DEPENDS "catkin")
set(tfr_executive_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_executive_EXEC_DEPENDS "roscpp" "tfr_msgs" "tfr_utilities" "geometry_msgs" "trajectory_msgs" "actionlib")
set(tfr_executive_RUN_DEPENDS "roscpp" "tfr_msgs" "tfr_utilities" "geometry_msgs" "trajectory_msgs" "actionlib")
set(tfr_executive_TEST_DEPENDS "gtest")
set(tfr_executive_DOC_DEPENDS )
set(tfr_executive_URL_WEBSITE "http://www.trickfirerobotics.com/")
set(tfr_executive_URL_BUGTRACKER "")
set(tfr_executive_URL_REPOSITORY "")
set(tfr_executive_DEPRECATED "")