set(_CATKIN_CURRENT_PACKAGE "tfr_aruco")
set(tfr_aruco_VERSION "0.0.0")
set(tfr_aruco_MAINTAINER "Levi Stoddard <levi.stoddard@trickfirerobotics.com>")
set(tfr_aruco_PACKAGE_FORMAT "2")
set(tfr_aruco_BUILD_DEPENDS "actionlib" "roscpp" "tfr_msgs" "message_runtime" "sensor_msgs" "tf2")
set(tfr_aruco_BUILD_EXPORT_DEPENDS "actionlib" "roscpp" "tfr_msgs")
set(tfr_aruco_BUILDTOOL_DEPENDS "catkin")
set(tfr_aruco_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_aruco_EXEC_DEPENDS "actionlib" "roscpp" "tfr_msgs" "cv_camera" "message_runtime" "sensor_msgs")
set(tfr_aruco_RUN_DEPENDS "actionlib" "roscpp" "tfr_msgs" "cv_camera" "message_runtime" "sensor_msgs")
set(tfr_aruco_TEST_DEPENDS )
set(tfr_aruco_DOC_DEPENDS )
set(tfr_aruco_URL_WEBSITE "")
set(tfr_aruco_URL_BUGTRACKER "")
set(tfr_aruco_URL_REPOSITORY "")
set(tfr_aruco_DEPRECATED "")