set(_CATKIN_CURRENT_PACKAGE "tfr_launch")
set(tfr_launch_VERSION "0.0.0")
set(tfr_launch_MAINTAINER "Collin Conway <collinsconway@gmail.com>, Adam Krpan <adam.krpan@outlook.com>")
set(tfr_launch_PACKAGE_FORMAT "2")
set(tfr_launch_BUILD_DEPENDS )
set(tfr_launch_BUILD_EXPORT_DEPENDS )
set(tfr_launch_BUILDTOOL_DEPENDS "catkin" "catkin")
set(tfr_launch_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_launch_EXEC_DEPENDS "xacro" "tfr_navigation" "tfr_visualization" "tfr_localization")
set(tfr_launch_RUN_DEPENDS "xacro" "tfr_navigation" "tfr_visualization" "tfr_localization")
set(tfr_launch_TEST_DEPENDS )
set(tfr_launch_DOC_DEPENDS )
set(tfr_launch_URL_WEBSITE "http://www.trickfirerobotics.com/")
set(tfr_launch_URL_BUGTRACKER "")
set(tfr_launch_URL_REPOSITORY "")
set(tfr_launch_DEPRECATED "")