set(_CATKIN_CURRENT_PACKAGE "tfr_utilities")
set(tfr_utilities_VERSION "0.0.0")
set(tfr_utilities_MAINTAINER "Ryan Berge <ryan.berge@trickfirerobotics.com>")
set(tfr_utilities_PACKAGE_FORMAT "2")
set(tfr_utilities_BUILD_DEPENDS "roscpp" "rospy" "nav_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "message_runtime" "tfr_msgs" "tf" "tf2" "tf2_ros" "tf2_geometry_msgs" "actionlib" "pcl_ros")
set(tfr_utilities_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "nav_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "message_runtime" "tfr_msgs" "tf" "tf2" "tf2_ros" "tf2_geometry_msgs" "actionlib" "pcl_ros")
set(tfr_utilities_BUILDTOOL_DEPENDS "catkin")
set(tfr_utilities_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_utilities_EXEC_DEPENDS "roscpp" "rospy" "nav_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "message_runtime" "tfr_msgs" "tf" "tf2" "tf2_ros" "tf2_geometry_msgs" "actionlib" "pcl_ros")
set(tfr_utilities_RUN_DEPENDS "roscpp" "rospy" "nav_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "message_runtime" "tfr_msgs" "tf" "tf2" "tf2_ros" "tf2_geometry_msgs" "actionlib" "pcl_ros")
set(tfr_utilities_TEST_DEPENDS "gtest")
set(tfr_utilities_DOC_DEPENDS )
set(tfr_utilities_URL_WEBSITE "http://www.trickfirerobotics.com/")
set(tfr_utilities_URL_BUGTRACKER "")
set(tfr_utilities_URL_REPOSITORY "")
set(tfr_utilities_DEPRECATED "")