set(_CATKIN_CURRENT_PACKAGE "tfr_sensor")
set(tfr_sensor_VERSION "0.0.0")
set(tfr_sensor_MAINTAINER "Ryan Berge <ryan.berge@trickfirerobotics.com>")
set(tfr_sensor_PACKAGE_FORMAT "2")
set(tfr_sensor_BUILD_DEPENDS "roscpp" "sensor_msgs" "tfr_msgs" "tfr_utilities" "geometry_msgs" "std_srvs" "nav_msgs" "tf2" "tf2_geometry_msgs" "robot_localization" "tf2_ros" "actionlib" "cv_bridge" "image_transport")
set(tfr_sensor_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "tfr_msgs" "tfr_utilities" "geometry_msgs" "std_srvs" "nav_msgs" "tf2" "tf2_geometry_msgs" "robot_localization" "tf2_ros" "actionlib" "cv_bridge" "image_transport")
set(tfr_sensor_BUILDTOOL_DEPENDS "catkin")
set(tfr_sensor_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_sensor_EXEC_DEPENDS "cv_camera" "xsens_driver" "duo3d_driver" "roscpp" "sensor_msgs" "tfr_msgs" "tfr_utilities" "geometry_msgs" "std_srvs" "nav_msgs" "tf2" "tf2_geometry_msgs" "robot_localization" "tf2_ros" "actionlib" "cv_bridge" "image_transport")
set(tfr_sensor_RUN_DEPENDS "cv_camera" "xsens_driver" "duo3d_driver" "roscpp" "sensor_msgs" "tfr_msgs" "tfr_utilities" "geometry_msgs" "std_srvs" "nav_msgs" "tf2" "tf2_geometry_msgs" "robot_localization" "tf2_ros" "actionlib" "cv_bridge" "image_transport")
set(tfr_sensor_TEST_DEPENDS "gtest")
set(tfr_sensor_DOC_DEPENDS )
set(tfr_sensor_URL_WEBSITE "http://www.trickfirerobotics.com/")
set(tfr_sensor_URL_BUGTRACKER "")
set(tfr_sensor_URL_REPOSITORY "")
set(tfr_sensor_DEPRECATED "")