set(_CATKIN_CURRENT_PACKAGE "tfr_visualization")
set(tfr_visualization_VERSION "0.0.0")
set(tfr_visualization_MAINTAINER "Collin Conway <collinsconway@gmail.com>, Adam Krpan <adam.krpan@outlook.com>")
set(tfr_visualization_PACKAGE_FORMAT "2")
set(tfr_visualization_BUILD_DEPENDS )
set(tfr_visualization_BUILD_EXPORT_DEPENDS )
set(tfr_visualization_BUILDTOOL_DEPENDS "catkin")
set(tfr_visualization_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_visualization_EXEC_DEPENDS "rviz")
set(tfr_visualization_RUN_DEPENDS "rviz")
set(tfr_visualization_TEST_DEPENDS )
set(tfr_visualization_DOC_DEPENDS )
set(tfr_visualization_URL_WEBSITE "http://www.trickfirerobotics.com/")
set(tfr_visualization_URL_BUGTRACKER "")
set(tfr_visualization_URL_REPOSITORY "")
set(tfr_visualization_DEPRECATED "")