set(_CATKIN_CURRENT_PACKAGE "tfr_mission_control")
set(tfr_mission_control_VERSION "0.3.10")
set(tfr_mission_control_MAINTAINER "Collin <collinsconway@gmail.com>")
set(tfr_mission_control_PACKAGE_FORMAT "2")
set(tfr_mission_control_BUILD_DEPENDS "rqt_gui" "rqt_gui_cpp" "tfr_msgs" "tfr_utilities" "roscpp" "actionlib")
set(tfr_mission_control_BUILD_EXPORT_DEPENDS "rqt_gui" "rqt_gui_cpp" "tfr_msgs" "tfr_utilities" "roscpp" "actionlib")
set(tfr_mission_control_BUILDTOOL_DEPENDS "catkin")
set(tfr_mission_control_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_mission_control_EXEC_DEPENDS "rqt_gui" "rqt_gui_cpp" "tfr_msgs" "tfr_utilities" "roscpp" "actionlib")
set(tfr_mission_control_RUN_DEPENDS "rqt_gui" "rqt_gui_cpp" "tfr_msgs" "tfr_utilities" "roscpp" "actionlib")
set(tfr_mission_control_TEST_DEPENDS "gtest")
set(tfr_mission_control_DOC_DEPENDS )
set(tfr_mission_control_URL_WEBSITE "")
set(tfr_mission_control_URL_BUGTRACKER "")
set(tfr_mission_control_URL_REPOSITORY "")
set(tfr_mission_control_DEPRECATED "")