set(_CATKIN_CURRENT_PACKAGE "tfr_msgs")
set(tfr_msgs_VERSION "0.0.0")
set(tfr_msgs_MAINTAINER "Collin Conway <collinsconway@gmail.com>")
set(tfr_msgs_PACKAGE_FORMAT "2")
set(tfr_msgs_BUILD_DEPENDS "message_generation" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "actionlib" "actionlib_msgs")
set(tfr_msgs_BUILD_EXPORT_DEPENDS "message_generation" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "actionlib" "actionlib_msgs")
set(tfr_msgs_BUILDTOOL_DEPENDS "catkin")
set(tfr_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_msgs_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "actionlib" "actionlib_msgs")
set(tfr_msgs_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "actionlib" "actionlib_msgs" "message_generation")
set(tfr_msgs_TEST_DEPENDS )
set(tfr_msgs_DOC_DEPENDS )
set(tfr_msgs_URL_WEBSITE "")
set(tfr_msgs_URL_BUGTRACKER "")
set(tfr_msgs_URL_REPOSITORY "")
set(tfr_msgs_DEPRECATED "")