set(_CATKIN_CURRENT_PACKAGE "tfr_localization")
set(tfr_localization_VERSION "0.0.0")
set(tfr_localization_MAINTAINER "Ryan Berge <ryan.berge@trickfirerobotics.com>")
set(tfr_localization_PACKAGE_FORMAT "2")
set(tfr_localization_BUILD_DEPENDS "roscpp" "tfr_msgs" "tfr_utilities" "actionlib" "geometry_msgs")
set(tfr_localization_BUILD_EXPORT_DEPENDS "roscpp" "tfr_msgs" "tfr_utilities" "actionlib" "geometry_msgs")
set(tfr_localization_BUILDTOOL_DEPENDS "catkin")
set(tfr_localization_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_localization_EXEC_DEPENDS "roscpp" "tfr_msgs" "tfr_utilities" "actionlib" "geometry_msgs")
set(tfr_localization_RUN_DEPENDS "roscpp" "tfr_msgs" "tfr_utilities" "actionlib" "geometry_msgs")
set(tfr_localization_TEST_DEPENDS "gtest")
set(tfr_localization_DOC_DEPENDS )
set(tfr_localization_URL_WEBSITE "http://www.trickfirerobotics.com/")
set(tfr_localization_URL_BUGTRACKER "")
set(tfr_localization_URL_REPOSITORY "")
set(tfr_localization_DEPRECATED "")