set(_CATKIN_CURRENT_PACKAGE "tfr_can")
set(tfr_can_VERSION "0.0.0")
set(tfr_can_MAINTAINER "Daniel Mamaghani <daniel.mamaghani@gmail.com>")
set(tfr_can_PACKAGE_FORMAT "2")
set(tfr_can_BUILD_DEPENDS "kacanopen")
set(tfr_can_BUILD_EXPORT_DEPENDS "kacanopen")
set(tfr_can_BUILDTOOL_DEPENDS "catkin")
set(tfr_can_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_can_EXEC_DEPENDS "kacanopen")
set(tfr_can_RUN_DEPENDS "kacanopen")
set(tfr_can_TEST_DEPENDS )
set(tfr_can_DOC_DEPENDS )
set(tfr_can_URL_WEBSITE "")
set(tfr_can_URL_BUGTRACKER "")
set(tfr_can_URL_REPOSITORY "")
set(tfr_can_DEPRECATED "")