set(_CATKIN_CURRENT_PACKAGE "tfr_moveit")
set(tfr_moveit_VERSION "0.3.0")
set(tfr_moveit_MAINTAINER "TrickFire Robotics <trickfirerobotics@gmail.com>")
set(tfr_moveit_PACKAGE_FORMAT "1")
set(tfr_moveit_BUILD_DEPENDS "tfr_description")
set(tfr_moveit_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "tfr_description")
set(tfr_moveit_BUILDTOOL_DEPENDS "catkin")
set(tfr_moveit_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_moveit_EXEC_DEPENDS "moveit_ros_move_group" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "tfr_description")
set(tfr_moveit_RUN_DEPENDS "moveit_ros_move_group" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "tfr_description")
set(tfr_moveit_TEST_DEPENDS )
set(tfr_moveit_DOC_DEPENDS )
set(tfr_moveit_URL_WEBSITE "http://moveit.ros.org/")
set(tfr_moveit_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(tfr_moveit_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(tfr_moveit_DEPRECATED "")