<?xml version="1.0"?>
<!-- Model of the arm without the joint that would atatch it to the base.
    used for simulation the arm without the base -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tfr_arm">

  <!-- attatch robot to world frame -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="turntable"/>
  </joint> 
  
  <!--DIGGING ARM-->
  <link name="turntable">
    <visual>
      <geometry>
        <cylinder radius="${turntable_radius}" length="${turntable_height}" />
      </geometry>
      <origin xyz="0 0 ${turntable_height/2}" rpy="0 0 ${pi}" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${turntable_radius}" length="${turntable_height}" />
      </geometry>
      <origin xyz="0 0 ${turntable_height/2}" rpy="0 0 ${pi}" />
    </collision>
    <!-- test -->
    <inertial>
      <mass value="${turntable_mass}" />
      <inertia ixx="${0.0833333 * turntable_mass * (3.0 * turntable_radius * turntable_radius + turntable_height * turntable_height)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * turntable_mass * (3.0 * turntable_radius * turntable_radius + turntable_height * turntable_height)}" iyz="0.0"
        izz="${0.5 * turntable_mass * turntable_radius * turntable_radius}" />
      <!--<inertia ixx="20.0" ixy="0.0" ixz="0.0" iyy="20.0" iyz="0.0" izz="20.0"/>-->
    </inertial>
  </link>

  <link name="lower_arm">
    <visual>
      <geometry>
        <box size="${lower_arm_height} ${lower_arm_width} ${lower_arm_primary_length}"/>
      </geometry>
      <origin xyz="${-lower_arm_height/2} 0 ${14*itom}" />
    </visual>
    <collision>
      <geometry>
        <box size="${lower_arm_height} ${lower_arm_width} ${lower_arm_primary_length}"/>
      </geometry>
      <origin xyz="${-lower_arm_height/2} 0 ${14*itom}" />
    </collision>
    <!-- test -->
    <inertial>
      <mass value="${lower_arm_mass}" />
      <inertia ixx="${0.0833333 * lower_arm_mass * (lower_arm_width*lower_arm_width + lower_arm_primary_length*lower_arm_primary_length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * lower_arm_mass * (lower_arm_height*lower_arm_height + lower_arm_primary_length*lower_arm_primary_length)}" iyz="0.0"
        izz="${0.0833333 * lower_arm_mass * (lower_arm_height*lower_arm_height + lower_arm_width*lower_arm_width)}" />
      <!--<inertia ixx="15.0" ixy="0.0" ixz="0.0" iyy="15.0" iyz="0.0" izz="15.0"/>-->
    </inertial>
  </link>

  <joint name="lower_arm_joint" type="revolute">
    <parent link="turntable" />
    <child link="lower_arm" />
    <axis xyz="0 1 0" />
    <origin xyz="${-2.165*itom} 0 ${turntable_height}" />
    <limit effort="1.0" velocity="1.0" lower="${lower_arm_min}"
          upper="${lower_arm_max}" />
  </joint>
  <transmission name="lower_arm_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="lower_arm_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface
      </hardwareInterface>
    </joint>
    <actuator name="lower_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface
      </hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </actuator>
  </transmission>
  
  <link name="lower_arm_bottom">
    <visual>
      <geometry>
        <box size="${0.25*itom} ${lower_arm_width} ${lower_arm_length - lower_arm_primary_length}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${0.25*itom} ${lower_arm_width} ${lower_arm_length - lower_arm_primary_length}"/>
      </geometry>
    </collision>
    <!-- test -->
    <inertial>
      <mass value=".23" />
      <inertia ixx="${0.0833333 * 2.3}" ixy="0.0" ixz="0.0" iyy="${0.0833333 * 2.3}" iyz="0.0" izz="${0.0833333 * 2.3}"/>
    </inertial>
  </link>
  <joint name="lower_arm_bottom_joint" type="fixed">
    <parent link="lower_arm" />
    <child link="lower_arm_bottom" />
    <origin xyz="${-0.125*itom} 0 ${(lower_arm_length - lower_arm_primary_length)/2}" />
  </joint>
  
  <link name="lower_arm_slope">
    <visual>
      <geometry>
        <box size="${0.25*itom} ${lower_arm_width} ${(lower_arm_length - lower_arm_primary_length) * sqrt2}"/>
      </geometry>
      <origin xyz="${0.125*itom} 0 ${-(lower_arm_length - lower_arm_primary_length) / 2 * sqrt2}" rpy="0 0 0" />
    </visual>
    <collision>
      <geometry>
        <box size="${0.25*itom} ${lower_arm_width} ${(lower_arm_length - lower_arm_primary_length) * sqrt2}"/>
      </geometry>
      <origin xyz="${0.125*itom} 0 ${-(lower_arm_length - lower_arm_primary_length) / 2 * sqrt2}" rpy="0 0 0" />
    </collision>
    <!-- test -->
    <inertial>
      <mass value=".23" />
      <inertia ixx="${0.0833333 * 2.3}" ixy="0.0" ixz="0.0" iyy="${0.0833333 * 2.3}" iyz="0.0" izz="${0.0833333 * 2.3}"/>
    </inertial>
  </link>
  <joint name="lower_arm_slope_joint" type="fixed">
    <parent link="lower_arm" />
    <child link="lower_arm_slope" />
    <origin xyz="${-lower_arm_height} 0 ${(lower_arm_length - lower_arm_primary_length)}" rpy="0 ${-44*dtor} 0"/>
  </joint>

  <link name="upper_arm">
    <visual>
      <geometry>
        <box size="${upper_arm_height} ${upper_arm_width} ${upper_arm_length}"/>
      </geometry>
      <origin xyz="${-upper_arm_height/2} 0 ${upper_arm_length/2}" />
    </visual>
    <collision>
      <geometry>
        <box size="${upper_arm_height} ${upper_arm_width} ${upper_arm_length}"/>
      </geometry>
      <origin xyz="${-upper_arm_height/2} 0 ${upper_arm_length/2}" />
    </collision>
    <!-- test -->
    <inertial>
      <mass value="${upper_arm_mass}" />
      <inertia ixx="${0.0833333 * upper_arm_mass * (upper_arm_width*upper_arm_width + upper_arm_length*upper_arm_length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * upper_arm_mass * (upper_arm_height*upper_arm_height + upper_arm_length*upper_arm_length)}" iyz="0.0"
        izz="${0.0833333 * upper_arm_mass * (upper_arm_height*upper_arm_height + upper_arm_width*upper_arm_width)}" />
    </inertial>
  </link>
  <joint name="upper_arm_joint" type="revolute">
    <parent link="lower_arm" />
    <child link="upper_arm" />
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${lower_arm_length}" />
    <limit effort="1.0" velocity="1.0" lower="${upper_arm_min}"
          upper="${upper_arm_max}" />
  </joint>
  <transmission name="upper_arm_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="upper_arm_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface
      </hardwareInterface>
    </joint>
    <actuator name="upper_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface
      </hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </actuator>
  </transmission>

  <link name="scoop">
    <visual>
      <geometry>
        <box size="${scoop_length} ${scoop_width} ${scoop_diameter/2}" />
      </geometry>
      <origin xyz="${scoop_length/2} 0 ${scoop_diameter/4}" />
    </visual>
    <collision>
      <geometry>
        <box size="${scoop_length} ${scoop_width} ${scoop_diameter/2}" />
      </geometry>
      <origin xyz="${scoop_length/2} 0 ${scoop_diameter/4}" />
    </collision>
    <!-- test -->
    <inertial>
      <mass value="${scoop_mass}" />
      <inertia ixx="${0.0833333 * scoop_mass * (scoop_width*scoop_width + (scoop_diameter/2)*(scoop_diameter/2))}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * scoop_mass * (scoop_length*scoop_length + (scoop_diameter/2)*(scoop_diameter/2))}" iyz="0.0"
        izz="${0.0833333 * scoop_mass * (scoop_length*scoop_length + scoop_width*scoop_width)}" />
    </inertial>
  </link>
  <joint name="scoop_joint" type="revolute">
    <parent link="upper_arm" />
    <child link="scoop" />
    <origin xyz="${1.5*itom} 0 ${upper_arm_length - (0.875*itom)}" />
    <axis xyz="0 1 0" />
    <limit effort="1.0" velocity="1.0" lower="${scoop_min}"
          upper="${scoop_max}" />
  </joint>
  <transmission name="scoop_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="scoop_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface
      </hardwareInterface>
    </joint>
    <actuator name="end_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface
      </hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </actuator>
  </transmission>
</robot>
