set(_CATKIN_CURRENT_PACKAGE "tfr_navigation")
set(tfr_navigation_VERSION "0.0.0")
set(tfr_navigation_MAINTAINER "Ryan Berge <ryan.berge@trickfirerobotics.com>")
set(tfr_navigation_PACKAGE_FORMAT "2")
set(tfr_navigation_BUILD_DEPENDS "tfr_msgs" "tfr_utilities" "roscpp")
set(tfr_navigation_BUILD_EXPORT_DEPENDS "tfr_msgs" "tfr_utilities" "roscpp")
set(tfr_navigation_BUILDTOOL_DEPENDS "catkin")
set(tfr_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(tfr_navigation_EXEC_DEPENDS "rtabmap_ros" "rtabmap" "move_base" "tfr_msgs" "tfr_utilities" "roscpp")
set(tfr_navigation_RUN_DEPENDS "rtabmap_ros" "rtabmap" "move_base" "tfr_msgs" "tfr_utilities" "roscpp")
set(tfr_navigation_TEST_DEPENDS "gtest")
set(tfr_navigation_DOC_DEPENDS )
set(tfr_navigation_URL_WEBSITE "http://www.trickfirerobotics.com/")
set(tfr_navigation_URL_BUGTRACKER "")
set(tfr_navigation_URL_REPOSITORY "")
set(tfr_navigation_DEPRECATED "")